[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$d.49xxhjTClF6D1HCCEEIA$MzJAyauvdaLqa1NC/XDKHqX3tFf6QOzn.8UZ5n5Nsy6xvMQecLkEicspDp.KnlVM37B886/w1ptWoEZQphVyBw
dev_mode = all,xml
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

